server:
    port: 8084
    
tomcat:
  ajp:
    port: 9094

masterkey:
    path: /opt/springservices/data/file.txt
   
logging:
    level:
        org.springframework.web: TRACE
        fr.home.mikedev: TRACE
