server:
    port: 8084
    
tomcat:
  ajp:
    port: 9094

masterkey:
    path: C:\Users\micha\Documents\dev\masterkey\devkey.txt
            
logging:
    level:
        org.springframework.web: TRACE
        fr.home.mikedev: TRACE